#!/usr/bin/env bash

# cd
alias ..='cd ..'

# ls
alias ls="ls -F"
alias l="ls -lAh"
alias ll="ls -l"
alias la='ls -A'

# git
alias gs='git status'
alias gpr='git pull --rebase'
alias gd='git diff'
alias gdc='git diff --cached'
alias ga='git add -u'
alias gst='git status'
alias grm="git status | grep deleted | awk '{print \$3}' | xargs git rm"

#tmux
alias tm="tmux"

# misc
alias reload='. ~/.bash_profile'


